spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: auth-service
          uri: lb://QUANTITY-SERVICE
          predicates:
            - Path=/auth/**
        - id: quantity-service
          uri: lb://QUANTITY-SERVICE
          predicates:
            - Path=/api/**

        - id: swagger-service
          uri: lb://QUANTITY-SERVICE
          predicates:
            - Path=/swagger-ui/**,/swagger-ui.html,/v3/api-docs/**

server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
jwt-Secret-Key: MySuperStrongSecretKeyThatIsAtLeast32CharsLong!!
debug: true
